.\" Process this file with
.\" groff -man -Tascii xxh.1
.\"
.TH XXH "1"
.SH NAME
xxh \- ssh connection manager.
.SH SYNOPSIS
.B xxh [command | conection_name]
.SH DESCRIPTION
.B xxh
manages your ssh connections and provides a helper
to set up you rsa keys so you don't have to type in
your password every time you connect to your remote.
Simply add the [-p] flag to the [add] command and xxh
will walk you through the set up. You will have to enter
your password twice. Once to to copy id_rsa.pub to the
remote, and again to append id_rsa.pub to the remotes
authorized_keys file.
.SH COMMANDS
.IP add
Add a connection to the ~/.xxhrc config.
.RS
.IP OPTIONS
.RS
.IP -p
Private connection, run rsa setup.
.RE
.IP EXAMPLE
xxh add -p custom_name user@host
.RE
.IP list
List all saved connections by name
.RS
.IP OPTIONS
.RS
.IP -v
List all saved connections with name, host and auth details
.RE
.RE
.IP edit
Edit a saved connection by name
.RS
.IP EXAMPLE
.RS
xxh edit custom_name
.RE
.RE
.IP delete
Delete a saved connection by name or all of them.
NOTE: This does not remove the rsa key from the
remote computers authorized_keys file.
.RS
.IP OPTIONS
.RS
.IP --all
Delete all saved connections
.RE
.IP EXAMPLE
xxh delete custom_name
.IP EXAMPLE
xxh delete --all
.RE
.SH FILES
.I ~/.xxhrc
.RS
Configuration file that holds all connection references
.RE
.SH AUTHOR
Xerxes Noble <xerxesnoble at gmail dot com>